name: The News Panels
description: "The news in comics."
icon: "/images/logo.png"

twitter: "@TheNewsPanels"
instagram: "thenewspanels"

url: "https://thenewspanels.com"
domainurl: "https://thenewspanels.com"
baseurl: "/"

collections:
    comics:
        output: true
        permalink: comics/:name/
    pages:
        output: true
        permalink: :name/

positions:
  - - rowStart: 1
      colStart: 1
      rowEnd: 3
      colEnd: 9
    - rowStart: 3
      colStart: 1
      rowEnd: 5
      colEnd: 7
    - rowStart: 5
      colStart: 1
      rowEnd: 7
      colEnd: 7
    - rowStart: 7
      colStart: 1
      rowEnd: 10
      colEnd: 7
    - rowStart: 3
      colStart: 7
      rowEnd: 10
      colEnd: 9
    - rowStart: 10
      colStart: 1
      rowEnd: 12
      colEnd: 9
    - rowStart: 12
      colStart: 1
      rowEnd: 14
      colEnd: 5
    - rowStart: 12
      colStart: 5
      rowEnd: 14
      colEnd: 9
  - - rowStart: 1
      colStart: 1
      rowEnd: 5
      colEnd: 4
    - rowStart: 1
      colStart: 4
      rowEnd: 3
      colEnd: 9
    - rowStart: 3
      colStart: 4
      rowEnd: 5
      colEnd: 9
    - rowStart: 5
      colStart: 1
      rowEnd: 7
      colEnd: 9
    - rowStart: 7
      colStart: 1
      rowEnd: 9
      colEnd: 5
    - rowStart: 7
      colStart: 5
      rowEnd: 9
      colEnd: 9
    - rowStart: 9
      colStart: 1
      rowEnd: 11
      colEnd: 9
    - rowStart: 11
      colStart: 1
      rowEnd: 13
      colEnd: 6
    - rowStart: 13
      colStart: 1
      rowEnd: 15
      colEnd: 6
    - rowStart: 11
      colStart: 6
      rowEnd: 15
      colEnd: 9

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

sass:
    sass_dir: ./css

plugins:
  - jekyll-sitemap
